### ISSUE TITLE
部分机型在BUTTONBIND时奔溃

### ISSUE THREAD

**Issue by XiqingLiu** [GeeTeam/gt3-android-sdk#12]
Process: com.example.geetestthr, PID: 31315
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException: println needs a message
at android.util.Log.println_native(Native Method)
at android.util.Log.i(Log.java:160)
at com.geetest.gt3unbindsdk.Bind.GT3GeetestBind.getajaxServer(GT3GeetestBind.java:419)
at com.geetest.gt3unbindsdk.Bind.GT3GeetestUtilsBind$O00000o0.O000000o(GT3GeetestUtilsBind.java:555)
at com.geetest.gt3unbindsdk.Bind.GT3GeetestUtilsBind$O00000o0.doInBackground(GT3GeetestUtilsBind.java:548)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841)

**Comment by YanLingHao** [comment]
麻烦请您提供相应的机型

**Comment by XiqingLiu** [comment]
安卓版本4.4.2，联想和模拟器都奔溃了

**Comment by YanLingHao** [comment]
这个问题已经修复 你集成下新SDK 注意集成方式有所修改 可以看Demo的演示代码。别用模拟器进行测试，用真机测试
