### ISSUE TITLE
请教极验以下问题有什么解决办法？极验证有依赖方式导入吗？

### ISSUE THREAD

**Issue by xbdcc** [GeeTeam/gt3-android-sdk#13]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/geetest/sdk/R$layout;
        at com.geetest.sdk.Bind.O0000O0o.onCreate(GT3GtDialogBind.java:292)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:395)
        at android.app.Dialog.show(Dialog.java:294)

自己封装library引用极验aar，module里面再引用导出的aar时出现该问题。试了fat-aar也没解决。请教有什么方法吗？极验不提供依赖形式吗？

**Comment by guxiaonian** [comment]
android Studio不支持在aar基础上二次封装aar，这边可以解压后以jar包形式，资源文件构建的形式封装二次aar。

**Comment by xbdcc** [comment]
试过了解压后把jar包和资源文件拷贝进自己的library，后导出aar到module里面引用也是会报这个错。后面把极验aar传到自己到maven库上依赖引用就没报错了。希望后面你们也提供依赖引用吧，依赖方式也好及时知道有新版本。
