### ISSUE TITLE
步步高家教机H8S 抛出NullPointerException

### ISSUE THREAD

**Issue by JunFreeman** [GeeTeam/gt3-android-sdk#19]
这台机器的系统是Android 4.2。
点击弹出那个图像框的时候 直接crash。麻烦帮忙看下。紧急。。。

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at android.webkit.WebView.loadUrl(WebView.java:855)
        at com.geetest.sdk.GT3GtWebView.O00000oo(GT3GtWebView.java:254)
        at com.geetest.sdk.GT3GtWebView.O00000oO(GT3GtWebView.java:244)
        at com.geetest.sdk.GT3GtWebView.O000000o(GT3GtWebView.java:249)
        at com.geetest.sdk.GT3GtWebView.O000000o(GT3GtWebView.java:46)
        at com.geetest.sdk.GT3GtWebView$O00000o.onPageStarted(GT3GtWebView.java:660)
        at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:325)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5043)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by JunFreeman** [comment]
cpu型号是 RK3188

**Comment by lchad** [comment]
@songsongbrother 请问这个问题是在哪个版本修复的?

**Comment by lchad** [comment]
你们 4.x 的 api 改动很大?我集成了之后,有些找不到了
